CC = gcc
CFLAGS = -Wall -Wextra -pthread
LIBS = -lws2_32

all: server client

server: server.c
	$(CC) $(CFLAGS) -o server server.c $(LIBS)

client: client.c
	$(CC) $(CFLAGS) -o client client.c $(LIBS)

clean:
	rm -f server client
